{
 "title": "pg_top_queries",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "vertamedia-clickhouse-datasource"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "select datname from pg.pg_stat_statements where created_hour >=  toStartOfHour(now()-interval 1 hour) group by datname order by datname"
   },
   {
    "name": "hostname",
    "query": "select hostname from pg.pg_stat_statements where datname IN ('$datname') and created_hour >=  toStartOfHour(now()-interval 1 hour) group by hostname order by hostname"
   },
   {
    "name": "column",
    "label": "sort_by",
    "query": "calls,total_exec_time+total_plan_time,rows,shared_blks_hit,shared_blks_read,shared_blks_dirtied,shared_blks_written,blk_read_time,blk_write_time,(total_exec_time+total_plan_time)/calls"
   },
   { "name": "limit", "query": "3,5,10,15" },
   { "name": "hide_superuser", "label": "Hide superuser", "query": "no,yes" },
   { "name": "query", "label": "Query Filter" }
  ]
 },
 "panels": [
  {
   "title": "Top $limit by $column Cumulative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Plan of top $limit query by $column",
     "type": "table",
     "description": "top $limit по сумме $column за заданный период времени\n\ntotal_time - общее время выполнения (cpu_time + io_time)\n\ncalls - количество выполнений\n\navg_latency - total_time / calls\n\nbuffers_read - сколько данных в сумме поднял запрос из OS (page cache + disc)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "contextWindowSize": "10",
       "dateTimeColDataType": "time",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    concat(username, '::', datname, '::', substring(query, 1, 3000)) AS query,\n    SUM(total_time) as total_time,\n    sum(calls) as calls,\n    total_time/calls as avg_latency,\n    8192* SUM(shared_blks_read + temp_blks_read + local_blks_read) AS buffers_read\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND query IN (\n    SELECT concat(username, '::', datname, '::', substring(query, 1, 3000))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY query\n",
       "query": "SELECT\n    concat(username, '::', datname, '::', substring(query, 1, 3000)) AS query,\n    SUM(total_exec_time+total_plan_time) as total_time,\n    sum(calls) as calls,\n    total_time/calls as avg_latency,\n    8192* SUM(shared_blks_read + temp_blks_read + local_blks_read) AS buffers_read\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND query IN (\n    SELECT concat(username, '::', datname, '::', substring(query, 1, 3000))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY query\n",
       "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    concat(username, '::', datname, '::', substring(query, 1, 3000)) AS query,\n    SUM(total_exec_time+total_plan_time) as total_time,\n    sum(calls) as calls,\n    total_time/calls as avg_latency,\n    8192* SUM(shared_blks_read + temp_blks_read + local_blks_read) AS buffers_read\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737994921)) AND(created_date <= toDate(1737996721)))\n    AND((created_at >= 1737994921) AND(created_at <= 1737996721))\n    AND created_hour >= toStartOfHour(toDateTime(1737994921))\n    AND created_hour <= toStartOfHour(toDateTime(1737996721))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND query IN (\n    SELECT concat(username, '::', datname, '::', substring(query, 1, 3000))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737994921)) AND(created_date <= toDate(1737996721)))\n        AND((created_at >= 1737994921) AND(created_at <= 1737996721))\n        AND created_hour >= toStartOfHour(toDateTime(1737994921))\n        AND created_hour <= toStartOfHour(toDateTime(1737996721))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 15)\nGROUP BY query",
       "round": "0s"
      }
     ]
    }
   ]
  },
  { "title": "detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "total_time",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    created_at * 1000 AS t,\r\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\r\n    avg(total_exec_time+total_plan_time) as value\r\nFROM pg.pg_stat_statements\r\nWHERE\r\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\r\n    AND((created_at >= $from) AND(created_at <= $to))\r\n    AND created_hour >= toStartOfHour(toDateTime($from))\r\n    AND created_hour <= toStartOfHour(toDateTime($to))\r\n    AND hostname = '$hostname'\r\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\r\n    AND q IN (\r\n    SELECT\r\n      concat(username, '::', datname, '::', substring(query, 1, 500))\r\n    FROM pg.pg_stat_statements\r\n    WHERE\r\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\r\n        AND((created_at >= $from) AND(created_at <= $to))\r\n        AND created_hour >= toStartOfHour(toDateTime($from))\r\n        AND created_hour <= toStartOfHour(toDateTime($to))\r\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\r\n        AND hostname = '$hostname'\r\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\r\n    GROUP BY\r\n        username,\r\n        datname,\r\n        query\r\n    ORDER BY sum($column) DESC\r\n    LIMIT $limit)\r\nGROUP BY t, q\r\nORDER BY t ASC",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\r\n    created_at * 1000 AS t,\r\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\r\n    avg(total_exec_time+total_plan_time) as value\r\nFROM pg.pg_stat_statements\r\nWHERE\r\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\r\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\r\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\r\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\r\n    AND hostname = 'LIGHTNING'\r\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\r\n    AND q IN (\r\n    SELECT\r\n      concat(username, '::', datname, '::', substring(query, 1, 500))\r\n    FROM pg.pg_stat_statements\r\n    WHERE\r\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\r\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\r\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\r\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\r\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\r\n        AND hostname = 'LIGHTNING'\r\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\r\n    GROUP BY\r\n        username,\r\n        datname,\r\n        query\r\n    ORDER BY sum(calls) DESC\r\n    LIMIT 5)\r\nGROUP BY t, q\r\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "calls",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nне учитывает время планирования запроса",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time/calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((total_exec_time+total_plan_time)/calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((total_exec_time+total_plan_time)/calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "cache hit ratio",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_hit / (shared_blks_hit + shared_blks_read)) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_hit / (shared_blks_hit + shared_blks_read)) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_hit / (shared_blks_hit + shared_blks_read)) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "shared_blks_read",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nTotal number of shared blocks read by the statement * 8192 (block size)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_read * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_read * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_read * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "temp files read and written",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nTotal number of temp blocks read and written by the statement * 8192 (block size)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((temp_blks_read + temp_blks_written) * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((temp_blks_read + temp_blks_written) * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((temp_blks_read + temp_blks_written) * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IO time",
   "type": "timeseries",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nTotal time the statement spent writing/reading blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(blk_read_time + blk_write_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(blk_read_time + blk_write_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=pg_top_queries3, user=1 */\nSELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(blk_read_time + blk_write_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n    AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n    AND created_hour >= toStartOfHour(toDateTime(1737992546))\n    AND created_hour <= toStartOfHour(toDateTime(1737996146))\n    AND hostname = 'LIGHTNING'\n    AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1737992546)) AND(created_date <= toDate(1737996146)))\n        AND((created_at >= 1737992546) AND(created_at <= 1737996146))\n        AND created_hour >= toStartOfHour(toDateTime(1737992546))\n        AND created_hour <= toStartOfHour(toDateTime(1737996146))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'LIGHTNING'\n        AND ('no' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(calls) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  }
 ]
}